paths:
  raw_tabular: data/raw/your_file.csv
  processed_tabular: data/processed/processed.parquet
  detections: data/external/detections.jsonl
  quantities: data/processed/quantities.parquet
  cost_indices_csv: data/external/cost_indices.csv
  packages_csv: data/external/packages.csv
  cost_breakdown: data/processed/cost_breakdown.parquet
  metrics_m3: outputs/reports/metrics_m3.json
  plots_dir: outputs/plots
  m1_preview_csv: outputs/reports/m1_preview.csv
  m1_schema_json: outputs/reports/m1_schema.json
  m2_preview_csv: outputs/reports/m2_preview.csv
  m3_preview_csv: outputs/reports/m3_preview.csv
  final_estimates: outputs/reports/final_estimates.parquet
  metrics_final: outputs/reports/metrics.json
  m4_preview_csv: outputs/reports/m4_preview.csv

  model_path: models/lgbm.pkl
  train_metrics: outputs/reports/model_metrics.json
  ml_predictions: outputs/reports/ml_predictions.parquet
  mlp_preview_csv: outputs/reports/ml_preview.csv

quant_rules:
  wall_height_ft: 9.5
  paint_wall_multiplier_by_room:
    Bedroom: 3.4
    "Living Room": 3.6
    Dining: 3.2
    "Kids Room": 3.4
    Kitchen: 3.0
    Bathroom: 2.2
    default: 3.2
  false_ceiling_ratio_by_type:
    None: 0.0
    POP: 0.85
    Gypsum: 0.9
    default: 0.0
  electrical_points_base:
    Bedroom: 12
    "Living Room": 18
    Dining: 10
    "Kids Room": 10
    Kitchen: 22
    Bathroom: 6
    default: 10
  electrical_area_scale: 0.015

rates:
  base_mpi: 1.0
  painting:
    material_per_sqft_by_quality:
      Economy: 16
      Standard: 24
      Premium: 34
    labor_per_sqft: 9
  flooring:
    material_per_sqft_by_type_quality:
      Ceramic_Tile:
        Economy: 60
        Standard: 85
        Premium: 120
      Vitrified_Tile:
        Economy: 75
        Standard: 110
        Premium: 150
    labor_per_sqft: 28
  ceiling:
    material_per_sqft_by_type_quality:
      POP:
        Economy: 65
        Standard: 85
        Premium: 120
      Gypsum:
        Economy: 80
        Standard: 105
        Premium: 140
    labor_per_sqft: 22
  electrical:
    per_point_material: 450
    per_point_labor: 180
  packages:
    kitchen:
      Basic_S: 35000
      Basic_L: 65000
      Premium: 120000
    bathroom:
      Basic: 20000
      Premium: 80000

cost:
  wastage_pct: 0.03
  contractor_overhead_pct: 0.12
  gst_rate: 0.18

fusion:
  w_tabular: 0.30
  w_quantity: 0.40
  w_ml: 0.30
  calibration_factor: 1.0

# Parameters for the ML model training stage
train:
  split:
    test_size: 0.2
    random_state: 42
  model:
    objective: regression_l1  # MAE
    n_estimators: 500
    learning_rate: 0.05
    num_leaves: 31
    max_depth: -1
    min_child_samples: 20
    subsample: 0.8
    colsample_bytree: 0.8
    n_jobs: -1